### ISSUE TITLE
I want to add some most useful algorithms code Like

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [UmangDalvadi/Hacktoberfest-2023#12]
1) K-way merge Algorithm

2) Stack Reduced Quick Sort

3) Merge sort combined with Insertion Sort

4) Prims, Topological, Kruskal's algorithm

5) DijKstra , Floyd Warshall ,bellman ford algorithm

6) Backtracking
a) Rat Maze
b) N-Queen
c) Sudoku
d) Sum of Subset

7) Activity selection , Huffman Encoding .

And please provide me the Access rights to make pull request : )

Please consider this under Hacktoberfest_2023 , I am interested to Contribute my self : )

**Comment by Bharath-KumarReddy** [comment]
Please provide me the access Rights so that I can make Pull Request .

![image](https://github.com/UmangDalvadi/Hacktoberfest-2023/assets/127650446/ba5b2936-486b-405e-ba54-34c9c0d1ba41)

**Comment by UmangDalvadi** [comment]
@Bharath-KumarReddy you can follow this as a reference: https://stackoverflow.com/questions/17857283/permission-denied-error-on-github-push/43672761#43672761

**Comment by Bharath-KumarReddy** [comment]
Yes sure : )
