### ISSUE TITLE
Need to add Sorting Algorithms

### ISSUE THREAD

**Issue by swaroop-2021** [UmangDalvadi/Hacktoberfest-2023#22]
I want to add the following sorting algorithms,

1) Bubble Sort
2) Selection Sort
3) Insertion Sort
4) Heap Sort
5) Merge Sort
6) Quick Sort

Please provide me the Access rights to make pull request : )
Please consider this under Hacktoberfest_2023, I am interested to Contribute : )

**Comment by UmangDalvadi** [comment]
@swaroop-2021 repo is excluded from hacktoberfest
